-- 문제: 입양 시각 구하기(1)
-- 핵심 배운 점: DATETIME 컬럼에서 HOUR() 함수로 시간대만 추출하고, BETWEEN으로 특정 범위 필터링
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;
