-- 문제: 카테고리 별 도서 판매량 집계하기
-- 핵심 배운 점: JOIN으로 두 테이블을 연결한 뒤, GROUP BY와 SUM을 결합하여 카테고리별 합계 산출
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
