-- 문제: 3월에 태어난 여성 회원 목록 출력하기
-- 핵심 배운 점: NULL 값 비교 시 등호(=)가 아닌 IS NOT NULL을 사용해야 한다는 데이터베이스 표준 원칙
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;