-- 문제: 조건에 맞는 도서 리스트 출력하기
-- 핵심 배운 점: DATE_FORMAT 함수로 날짜 형식을 지정하고, YEAR 함수로 특정 연도만 추출하여 비교
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;