-- 문제: 조건에 부합하는 중고거래 댓글 조회하기
-- 핵심 배운 점: JOIN 사용 시 테이블에 Alias(별칭)를 부여하고, 테이블명.컬럼명 형식으로 명시하여 모호성 에러 방지
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;